name: front CI/CD Prod

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          always-auth: true
          
      - name: Install dependencies
        run: |
          npm install
      - name: Build app
        run: |
          # npm run build and ignore eslint errors
          npm run build -- --max-warnings=0
