name: Docker Image CI/CD Prod

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  

      - name: Install dependencies
        run: |
          npm install

      - name: Build app
        run: |
          # npm run build and ignore eslint errors
          npm run build -- --max-warnings=0

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy App
        run: |
          cd build
          scp -r ./build root@vps-ovh:/build-front
