name: Docker Image CI/CD Prod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  CI-CD:
    name: Building and deploy Image gametrip-front
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build project with npm
        run: npm install && npm run build

      - name: Build Docker Image
        run: docker build --no-cache --file ./dockerfile --tag ${{ secrets.REGISTRY_NAME }}/gametrip-front:tag ./
      
      - name: Push Docker Image to Registry
        run: docker push ${{ secrets.REGISTRY_NAME }}/gametrip-front:tag
      
      - name: PUT Request Action to update Stack
        uses: fjogeleit/http-request-action@v1.13.0
        with:
          url: '${{ secrets.PORTAINER_UPDATE_STACK_FRONT_PROD_URL }}'
          method: 'PUT'
          timeout: 20000
          customHeaders: '${{ secrets.CUSTOM_HEADERS }}'
          data: '${{ vars.PORTAINER_UPDATE_STACK_FRONT_PROD }}'