name: Docker Image CI/CD Prod

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Deploy Frontend
        run: |
          npm install
          npm run build
